# Site settings
title: "Lukas Normantas"
description: "A single page resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Lukas Normantas"
resume_title:                   "Computer Science, Final Year Student"
resume_contact_email:           "me@lukasn.com"
resume_contact_telephone:       "07397300540"
# resume_contact_address:       ""
# resume_header_contact_info:   ""
resume_header_intro: "<p>Hello! I'm quick to adapt to new technologies, motivated about ambitious projects and love to try new things. I have worked as a Software Engineer previously and have now secured a role as a System Architect following my graduation.</p>"

resume_looking_for_work:        "no"
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/xylust"
  # resume_twitter_url:           ""
  # resume_dribbble_url:          ""
  # resume_facebook_url:          ""
  resume_linkedin_url:          "https://www.linkedin.com/in/lukinskas/"
  # resume_instagram_url:         ""
  resume_website_url:           "https://lukasn.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
