# Site settings
title: "Lukas Normantas"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Lukas Normantas"
resume_title:                   "Computer Science, Final Year Student"
resume_contact_email:           "lukasnrm@gmail.com"
resume_contact_telephone:       "07397300540"
# resume_contact_address:         "742 Evergreen Terrace, Springfield"
# resume_header_contact_info: "742 Evergreen Terrace, Springfield | 555-7334 | homerjsimpson@youremailaddress.com"
resume_header_intro: "<p>Hello! I'm quick to adapt to new technologies, motivated about ambitious projects and love to try new things. I have worked as a Software Engineer previously and have now secured a role as a System Architect following my graduation.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/xylust"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/lukinskas/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://lukasn.com/"
resume_print_social_links:      true

# Design settings
resume_theme:                   default
